application: perfect-entry-86804
version: 1
runtime: python27
api_version: 1
threadsafe: true


env_variables:
  DJANGO_SETTINGS_MODULE: 'blinc.settings'

handlers:
- url: /static
  static_dir: blinc/static


libraries:
- name: django
  version: "1.5"

builtins:
- django_wsgi: on
